CREATE DATABASE swetestdb;
\c swetestdb;

CREATE TABLE test(id INT PRIMARY KEY, name VARCHAR (100) NOT NULL);
INSERT INTO test VALUES (11,e);
INSERT INTO test VALUES (22,d);
INSERT INTO test VALUES (33,c);
INSERT INTO test VALUES (44,b);
INSERT INTO test VALUES (55,a);
