CREATE DATABASE swetestdb;
\c swetestdb;
CREATE TABLE test(id INT PRIMARY KEY);
INSERT INTO test VALUES (11);
INSERT INTO test VALUES (22);
INSERT INTO test VALUES (33);
INSERT INTO test VALUES (44);
INSERT INTO test VALUES (55);
